### ISSUE TITLE
Document preferences against racially charged jargon

### ISSUE THREAD

**Issue by zweishar** [adaptdk/usa-documentation#11]
There is a lot of racially charged jargon in this industry that I don't want to perpetuate at our company. The original intent may not have been racially oriented (at least not directly), but the effect in current times isn't ideal. We can easily change the terms we use for these things.

Examples include:

- `master branch` => `main branch`
- `white list / black list` => `allowed list => disallowed list`
- `master / slave` => `primary => dependent` (not sure I love this one, but the original is terrible)

**Comment by marvil07-adapt** [comment]
@zweishar I have just added an extra commit about this, pointing to IETF draft [Terminology, Power and Oppressive Language](https://tools.ietf.org/id/draft-knodel-terminology-00.html).

**Comment by zweishar** [comment]
Love it, thank you @marvil07. I haven't seen that before + it's a nice resource.
