### ISSUE TITLE
Document the "open backlog" approach to workflow

### ISSUE THREAD

**Issue by zweishar** [adaptdk/usa-documentation#17]
On the ACSF project, we identified that letting devs take tickets from the backlog as they choose (rather than explicitly assigning tickets) was positive. Let's document that + make it a regular practice.

**Comment by marvil07-adapt** [comment]
@zweishar Indeed, the open backlog approach worked great.
Thanks for documenting it here!

I added a couple of small commits, one a typo fix, the other a suggestion to use tags, so tickets are easier to filter.

New commits on `17-ticket-asignment` topic branch and related PR #23
- 32c8229 #17 Fix typo
- b275915 #17 Add note about issue tags

@jesseday assigning it to you for the final review.
