### ISSUE TITLE
Brainstorming suggestions

### ISSUE THREAD

**Issue by marvil07-adapt** [adaptdk/usa-documentation#18]
- better issue templates (more to come)
- unify format wrapping
- code-reviews: replace `handoff`?
- contrib: general place to communicate about this on adapt?
- developer-onboarding: lastpass
- project-workflow: unify with checklist
- project-workflow: ho to group tickets, e.g. sprints vs subprojects,
  i.e. milestone vs project
- project-workflow: kanban vs scrum, this influences how we approach the
  tickets, milestones, and more.
- project-workflow: Done pipeline not really used on the project I 
  participated into; it may be useful for maintenance projects. E.g. Done
  pipeline may be relevant on a kanban board but maybe not on a scrum board.
  Instead suggest to create a ticket for deployment, and while the deployment
  is being performed, find out what has been added?
- standups: consider non-live, e.g. via text on slack or similar
- standups: after-meetings for specifics?

**Comment by jesseday** [comment]
Lots of good stuff here.

> project-workflow: unify with checklist

Love this idea.  A checklist would be a nice reference.


> project-workflow: ho to group tickets, e.g. sprints vs subprojects,
i.e. milestone vs project

I don't have an answer but I'd love to hear more about what you're thinking.  Do you have an initial idea of how you would want things to be structured?  I imagine that it may depend on the project?  I feel like I've usually done sprints and milestones.  What would a projects, subprojects setup look like?

> standups: consider non-live, e.g. via text on slack or similar

I think non-live can work really well.  I think the most helpful part about standups for me is flagging issues and talking about them on after meetings.  How are you thinking that may work?  Could there be a standing time for issue meetings if people need them?

**Comment by jesseday** [comment]
> standups: consider non-live, e.g. via text on slack or similar

I added a daily check-in for Darius and I in basecamp for Workhuman.  We'll see how it goes.  It's a small project so I think it could work well.

**Comment by marvil07-adapt** [comment]
I have started with one of the changes.

New commits on new `18-brainstorming` topic branch and related new PR #22
- 8a1cd39 #18 Unify project workflow setup section into existing new project checklist

**Comment by marvil07-adapt** [comment]
> better issue templates (more to come)

I have suggested changes related to issue templates now.

New commits on `18-brainstorming` topic branch and related new PR #22 
- 7c5bc28 #18 Add an issue template
- 29969cf #18 Rename to lowercase pull request template
- c13dcb1 #18 Move pull request template instructions related to github to the readme
- bbb3947 #18 Document a bit the process to fill the pull request

**Comment by marvil07-adapt** [comment]
It has been a while, so I have added some extra commits to the related PR, and tried to close the pending items.
Anything now not covered on the PR is likely something that should be examined/added independently.

Here a recap of the status.

> - better issue templates (more to come)
> - developer-onboarding: lastpass
> - project-workflow: unify with checklist
> - project-workflow: Done pipeline not really used on the project I 
>   participated into; it may be useful for maintenance projects. E.g. Done
>   pipeline may be relevant on a kanban board but maybe not on a scrum board.
>   Instead suggest to create a ticket for deployment, and while the deployment
>   is being performed, find out what has been added?
> - standups: consider non-live, e.g. via text on slack or similar
> - standups: after-meetings for specifics?

Implemented at related PR.

> - code-reviews: replace `handoff`?

I was not convinced of the use of the words, but it seems like it was mostly an impression.
I was thinking on relays, but it is not truly better.
At the end I have just changed it to use `hand-off` for easier reading.

> - contrib: general place to communicate about this on adapt?

Already added via 5202a25.

> - unify format wrapping
> - project-workflow: how to group tickets, e.g. sprints vs subprojects,
>   i.e. milestone vs project
> - project-workflow: kanban vs scrum, this influences how we approach the
>   tickets, milestones, and more.

Pending, please see the new #24 and #25.
@jesseday let us continue the conversation there to avoid making this one too broad.

New commits on `18-brainstorming` topic branch and related PR #22

- 2845f72 #18 code-reviews, replace handoff with hand-offs
- 1cc4843 #18 Add a note about lastpass
- 1d15db6 #18 standups, document after-meetings criteria
- fe0a105 #18 standups, suggest non-live approach

@zweishar, @jesseday, PR now ready for review.
