### ISSUE TITLE
Document Dev Library

### ISSUE THREAD

**Issue by jesseday** [adaptdk/usa-documentation#3]
Let's make a section to note where devs can find any resources that we already have and how they may go about requesting new ones.

**Comment by jesseday** [comment]
Fyi @zweishar if you purchase the grumpy programmer testing book and put it somewhere, you can either write the section or tag me in a comment here and I'll update the docs.

**Comment by zweishar** [comment]
@jesseday I added a section on learning materials + bought the book we where talking about. I'm going to close this issue for now, but feel free to re-open if you feel like we need further documentation.
